#! /usr/bin/python
# EASY-INSTALL-ENTRY-SCRIPT: 'distribute==0.6.24dev-r0','console_scripts','easy_install'
#__requires__ = 'distribute==0.6.24dev-r0'
__requires__ = 'setuptools==0.7.2'
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.exit(
        load_entry_point('setuptools==0.7.2', 'console_scripts', 'easy_install')()
    )
